# Generated by Django 4.1 on 2022-08-13 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0002_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
