# Generated by Django 4.1 on 2022-08-13 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0003_startup_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='status',
        ),
        migrations.AlterField(
            model_name='startup',
            name='investors',
            field=models.ManyToManyField(blank=True, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
