# Generated by Django 4.1 on 2022-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0004_remove_startup_status_alter_startup_investors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='subject',
            field=models.TextField(),
        ),
    ]
