# Generated by Django 4.1 on 2022-08-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0006_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='innovate.startup'),
            preserve_default='True',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
