# Generated by Django 4.1 on 2022-08-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0011_remove_startup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='subject',
        ),
    ]
