# Generated by Django 4.0.1 on 2022-08-13 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innovate', '0013_startup_image_startup_name_alter_user_favourites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='business_plan',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
